// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agv_page_type::AgvPage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct AgvPageArgs {
    pub map_id: String,
    pub search: String,
    pub after_agv_id: Option<String>,
    pub limit: u32,
}

impl __sdk::InModule for AgvPageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `agv_page`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait agv_page {
    fn agv_page(&self, map_id: String, search: String, after_agv_id: Option<String>, limit: u32) {
        self.agv_page_then(map_id, search, after_agv_id, limit, |_, _| {});
    }

    fn agv_page_then(
        &self,
        map_id: String,
        search: String,
        after_agv_id: Option<String>,
        limit: u32,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<AgvPage, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl agv_page for super::RemoteProcedures {
    fn agv_page_then(
        &self,
        map_id: String,
        search: String,
        after_agv_id: Option<String>,
        limit: u32,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<AgvPage, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, AgvPage>(
            "agv_page",
            AgvPageArgs {
                map_id,
                search,
                after_agv_id,
                limit,
            },
            __callback,
        );
    }
}
