// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agv_error_type::AgvError;
use super::agv_state_type::AgvState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agv_state`.
///
/// Obtain a handle from the [`AgvStateTableAccess::agv_state`] method on [`super::RemoteTables`],
/// like `ctx.db.agv_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv_state().on_insert(...)`.
pub struct AgvStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgvState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `agv_state`.
pub struct AgvStateTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AgvStateTableAccessor {
    type Row = AgvState;
    type Handle<'db> = AgvStateTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.agv_state()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agv_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgvStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgvStateTableHandle`], which mediates access to the table `agv_state`.
    fn agv_state(&self) -> AgvStateTableHandle<'_>;
}

impl AgvStateTableAccess for super::RemoteTables {
    fn agv_state(&self) -> AgvStateTableHandle<'_> {
        AgvStateTableHandle {
            imp: self.imp.get_table::<AgvState>("agv_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgvStateInsertCallbackId(__sdk::CallbackId);
pub struct AgvStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AgvStateTableHandle<'ctx> {
    type Row = AgvState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgvState> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AgvStateTableHandle<'ctx> {
    type Row = AgvState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgvState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgvStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvStateInsertCallbackId {
        AgvStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgvStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvStateDeleteCallbackId {
        AgvStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AgvStateTableHandle<'ctx> {
    type InsertCallbackId = AgvStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvStateInsertCallbackId {
        AgvStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AgvStateTableHandle<'ctx> {
    type DeleteCallbackId = AgvStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvStateDeleteCallbackId {
        AgvStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgvStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgvStateTableHandle<'ctx> {
    type UpdateCallbackId = AgvStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvStateUpdateCallbackId {
        AgvStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AgvStateTableHandle<'ctx> {
    type UpdateCallbackId = AgvStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvStateUpdateCallbackId {
        AgvStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agv_id` unique index on the table `agv_state`,
/// which allows point queries on the field of the same name
/// via the [`AgvStateAgvIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv_state().agv_id().find(...)`.
pub struct AgvStateAgvIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgvState, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgvStateTableHandle<'ctx> {
    /// Get a handle on the `agv_id` unique index on the table `agv_state`.
    pub fn agv_id(&self) -> AgvStateAgvIdUnique<'ctx> {
        AgvStateAgvIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agv_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgvStateAgvIdUnique<'ctx> {
    /// Find the subscribed row whose `agv_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgvState> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgvState>("agv_state");
    _table.add_unique_constraint::<String>("agv_id", |row| &row.agv_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgvState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgvState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgvState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agv_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgvState`.
    fn agv_state(&self) -> __sdk::__query_builder::Table<AgvState>;
}

impl agv_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn agv_state(&self) -> __sdk::__query_builder::Table<AgvState> {
        __sdk::__query_builder::Table::new("agv_state")
    }
}
