// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agv_type::Agv;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agv`.
///
/// Obtain a handle from the [`AgvTableAccess::agv`] method on [`super::RemoteTables`],
/// like `ctx.db.agv()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv().on_insert(...)`.
pub struct AgvTableHandle<'ctx> {
    imp: __sdk::TableHandle<Agv>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `agv`.
pub struct AgvTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AgvTableAccessor {
    type Row = Agv;
    type Handle<'db> = AgvTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.agv()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agv`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgvTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgvTableHandle`], which mediates access to the table `agv`.
    fn agv(&self) -> AgvTableHandle<'_>;
}

impl AgvTableAccess for super::RemoteTables {
    fn agv(&self) -> AgvTableHandle<'_> {
        AgvTableHandle {
            imp: self.imp.get_table::<Agv>("agv"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgvInsertCallbackId(__sdk::CallbackId);
pub struct AgvDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AgvTableHandle<'ctx> {
    type Row = Agv;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Agv> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AgvTableHandle<'ctx> {
    type Row = Agv;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Agv> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgvInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvInsertCallbackId {
        AgvInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgvDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvDeleteCallbackId {
        AgvDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AgvTableHandle<'ctx> {
    type InsertCallbackId = AgvInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvInsertCallbackId {
        AgvInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AgvTableHandle<'ctx> {
    type DeleteCallbackId = AgvDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvDeleteCallbackId {
        AgvDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgvUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgvTableHandle<'ctx> {
    type UpdateCallbackId = AgvUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvUpdateCallbackId {
        AgvUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AgvTableHandle<'ctx> {
    type UpdateCallbackId = AgvUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvUpdateCallbackId {
        AgvUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agv_id` unique index on the table `agv`,
/// which allows point queries on the field of the same name
/// via the [`AgvAgvIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv().agv_id().find(...)`.
pub struct AgvAgvIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Agv, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgvTableHandle<'ctx> {
    /// Get a handle on the `agv_id` unique index on the table `agv`.
    pub fn agv_id(&self) -> AgvAgvIdUnique<'ctx> {
        AgvAgvIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agv_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgvAgvIdUnique<'ctx> {
    /// Find the subscribed row whose `agv_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Agv> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Agv>("agv");
    _table.add_unique_constraint::<String>("agv_id", |row| &row.agv_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Agv>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Agv>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Agv`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agvQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Agv`.
    fn agv(&self) -> __sdk::__query_builder::Table<Agv>;
}

impl agvQueryTableAccess for __sdk::QueryTableAccessor {
    fn agv(&self) -> __sdk::__query_builder::Table<Agv> {
        __sdk::__query_builder::Table::new("agv")
    }
}
