// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::connection_state_type::ConnectionState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgvConnection {
    pub agv_id: String,
    pub connection_state: ConnectionState,
    pub sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for AgvConnection {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgvConnection`.
///
/// Provides typed access to columns for query building.
pub struct AgvConnectionCols {
    pub agv_id: __sdk::__query_builder::Col<AgvConnection, String>,
    pub connection_state: __sdk::__query_builder::Col<AgvConnection, ConnectionState>,
    pub sent_at: __sdk::__query_builder::Col<AgvConnection, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgvConnection {
    type Cols = AgvConnectionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgvConnectionCols {
            agv_id: __sdk::__query_builder::Col::new(table_name, "agv_id"),
            connection_state: __sdk::__query_builder::Col::new(table_name, "connection_state"),
            sent_at: __sdk::__query_builder::Col::new(table_name, "sent_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgvConnection`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgvConnectionIxCols {
    pub agv_id: __sdk::__query_builder::IxCol<AgvConnection, String>,
    pub connection_state: __sdk::__query_builder::IxCol<AgvConnection, ConnectionState>,
}

impl __sdk::__query_builder::HasIxCols for AgvConnection {
    type IxCols = AgvConnectionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgvConnectionIxCols {
            agv_id: __sdk::__query_builder::IxCol::new(table_name, "agv_id"),
            connection_state: __sdk::__query_builder::IxCol::new(table_name, "connection_state"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgvConnection {}
