// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agv_error_type::AgvError;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgvStateFields {
    pub order_id: String,
    pub last_node_id: String,
    pub driving: bool,
    pub paused: bool,
    pub charging: bool,
    pub error: Option<AgvError>,
}

impl __sdk::InModule for AgvStateFields {
    type Module = super::RemoteModule;
}
