// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Agv {
    pub agv_id: String,
    pub manufacturer: String,
    pub serial_number: String,
    pub map_id: String,
}

impl __sdk::InModule for Agv {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Agv`.
///
/// Provides typed access to columns for query building.
pub struct AgvCols {
    pub agv_id: __sdk::__query_builder::Col<Agv, String>,
    pub manufacturer: __sdk::__query_builder::Col<Agv, String>,
    pub serial_number: __sdk::__query_builder::Col<Agv, String>,
    pub map_id: __sdk::__query_builder::Col<Agv, String>,
}

impl __sdk::__query_builder::HasCols for Agv {
    type Cols = AgvCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgvCols {
            agv_id: __sdk::__query_builder::Col::new(table_name, "agv_id"),
            manufacturer: __sdk::__query_builder::Col::new(table_name, "manufacturer"),
            serial_number: __sdk::__query_builder::Col::new(table_name, "serial_number"),
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Agv`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgvIxCols {
    pub agv_id: __sdk::__query_builder::IxCol<Agv, String>,
}

impl __sdk::__query_builder::HasIxCols for Agv {
    type IxCols = AgvIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgvIxCols {
            agv_id: __sdk::__query_builder::IxCol::new(table_name, "agv_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Agv {}
