// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agv_error_type::AgvError;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgvState {
    pub agv_id: String,
    pub order_id: String,
    pub last_node_id: String,
    pub driving: bool,
    pub paused: bool,
    pub charging: bool,
    pub error: Option<AgvError>,
    pub updated_at: __sdk::Timestamp,
    pub alert: bool,
    pub state_sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for AgvState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgvState`.
///
/// Provides typed access to columns for query building.
pub struct AgvStateCols {
    pub agv_id: __sdk::__query_builder::Col<AgvState, String>,
    pub order_id: __sdk::__query_builder::Col<AgvState, String>,
    pub last_node_id: __sdk::__query_builder::Col<AgvState, String>,
    pub driving: __sdk::__query_builder::Col<AgvState, bool>,
    pub paused: __sdk::__query_builder::Col<AgvState, bool>,
    pub charging: __sdk::__query_builder::Col<AgvState, bool>,
    pub error: __sdk::__query_builder::Col<AgvState, Option<AgvError>>,
    pub updated_at: __sdk::__query_builder::Col<AgvState, __sdk::Timestamp>,
    pub alert: __sdk::__query_builder::Col<AgvState, bool>,
    pub state_sent_at: __sdk::__query_builder::Col<AgvState, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgvState {
    type Cols = AgvStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgvStateCols {
            agv_id: __sdk::__query_builder::Col::new(table_name, "agv_id"),
            order_id: __sdk::__query_builder::Col::new(table_name, "order_id"),
            last_node_id: __sdk::__query_builder::Col::new(table_name, "last_node_id"),
            driving: __sdk::__query_builder::Col::new(table_name, "driving"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
            charging: __sdk::__query_builder::Col::new(table_name, "charging"),
            error: __sdk::__query_builder::Col::new(table_name, "error"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            alert: __sdk::__query_builder::Col::new(table_name, "alert"),
            state_sent_at: __sdk::__query_builder::Col::new(table_name, "state_sent_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgvState`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgvStateIxCols {
    pub agv_id: __sdk::__query_builder::IxCol<AgvState, String>,
    pub alert: __sdk::__query_builder::IxCol<AgvState, bool>,
}

impl __sdk::__query_builder::HasIxCols for AgvState {
    type IxCols = AgvStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgvStateIxCols {
            agv_id: __sdk::__query_builder::IxCol::new(table_name, "agv_id"),
            alert: __sdk::__query_builder::IxCol::new(table_name, "alert"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgvState {}
