// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agv_connection_type::AgvConnection;
use super::connection_state_type::ConnectionState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agv_connection`.
///
/// Obtain a handle from the [`AgvConnectionTableAccess::agv_connection`] method on [`super::RemoteTables`],
/// like `ctx.db.agv_connection()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv_connection().on_insert(...)`.
pub struct AgvConnectionTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgvConnection>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `agv_connection`.
pub struct AgvConnectionTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AgvConnectionTableAccessor {
    type Row = AgvConnection;
    type Handle<'db> = AgvConnectionTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.agv_connection()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agv_connection`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgvConnectionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgvConnectionTableHandle`], which mediates access to the table `agv_connection`.
    fn agv_connection(&self) -> AgvConnectionTableHandle<'_>;
}

impl AgvConnectionTableAccess for super::RemoteTables {
    fn agv_connection(&self) -> AgvConnectionTableHandle<'_> {
        AgvConnectionTableHandle {
            imp: self.imp.get_table::<AgvConnection>("agv_connection"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgvConnectionInsertCallbackId(__sdk::CallbackId);
pub struct AgvConnectionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AgvConnectionTableHandle<'ctx> {
    type Row = AgvConnection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgvConnection> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AgvConnectionTableHandle<'ctx> {
    type Row = AgvConnection;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgvConnection> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgvConnectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvConnectionInsertCallbackId {
        AgvConnectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvConnectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgvConnectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvConnectionDeleteCallbackId {
        AgvConnectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvConnectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AgvConnectionTableHandle<'ctx> {
    type InsertCallbackId = AgvConnectionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvConnectionInsertCallbackId {
        AgvConnectionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgvConnectionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AgvConnectionTableHandle<'ctx> {
    type DeleteCallbackId = AgvConnectionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgvConnectionDeleteCallbackId {
        AgvConnectionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgvConnectionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgvConnectionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgvConnectionTableHandle<'ctx> {
    type UpdateCallbackId = AgvConnectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvConnectionUpdateCallbackId {
        AgvConnectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvConnectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AgvConnectionTableHandle<'ctx> {
    type UpdateCallbackId = AgvConnectionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgvConnectionUpdateCallbackId {
        AgvConnectionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgvConnectionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agv_id` unique index on the table `agv_connection`,
/// which allows point queries on the field of the same name
/// via the [`AgvConnectionAgvIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agv_connection().agv_id().find(...)`.
pub struct AgvConnectionAgvIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgvConnection, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgvConnectionTableHandle<'ctx> {
    /// Get a handle on the `agv_id` unique index on the table `agv_connection`.
    pub fn agv_id(&self) -> AgvConnectionAgvIdUnique<'ctx> {
        AgvConnectionAgvIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agv_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgvConnectionAgvIdUnique<'ctx> {
    /// Find the subscribed row whose `agv_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgvConnection> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgvConnection>("agv_connection");
    _table.add_unique_constraint::<String>("agv_id", |row| &row.agv_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgvConnection>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgvConnection>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgvConnection`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agv_connectionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgvConnection`.
    fn agv_connection(&self) -> __sdk::__query_builder::Table<AgvConnection>;
}

impl agv_connectionQueryTableAccess for __sdk::QueryTableAccessor {
    fn agv_connection(&self) -> __sdk::__query_builder::Table<AgvConnection> {
        __sdk::__query_builder::Table::new("agv_connection")
    }
}
