// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::fleet_stats_row_type::FleetStatsRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `fleet_stats`.
///
/// Obtain a handle from the [`FleetStatsTableAccess::fleet_stats`] method on [`super::RemoteTables`],
/// like `ctx.db.fleet_stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.fleet_stats().on_insert(...)`.
pub struct FleetStatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FleetStatsRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `fleet_stats`.
pub struct FleetStatsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for FleetStatsTableAccessor {
    type Row = FleetStatsRow;
    type Handle<'db> = FleetStatsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.fleet_stats()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `fleet_stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FleetStatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FleetStatsTableHandle`], which mediates access to the table `fleet_stats`.
    fn fleet_stats(&self) -> FleetStatsTableHandle<'_>;
}

impl FleetStatsTableAccess for super::RemoteTables {
    fn fleet_stats(&self) -> FleetStatsTableHandle<'_> {
        FleetStatsTableHandle {
            imp: self.imp.get_table::<FleetStatsRow>("fleet_stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FleetStatsInsertCallbackId(__sdk::CallbackId);
pub struct FleetStatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for FleetStatsTableHandle<'ctx> {
    type Row = FleetStatsRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FleetStatsRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for FleetStatsTableHandle<'ctx> {
    type Row = FleetStatsRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FleetStatsRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FleetStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetStatsInsertCallbackId {
        FleetStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FleetStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetStatsDeleteCallbackId {
        FleetStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for FleetStatsTableHandle<'ctx> {
    type InsertCallbackId = FleetStatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetStatsInsertCallbackId {
        FleetStatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FleetStatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for FleetStatsTableHandle<'ctx> {
    type DeleteCallbackId = FleetStatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FleetStatsDeleteCallbackId {
        FleetStatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FleetStatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FleetStatsRow>("fleet_stats");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FleetStatsRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FleetStatsRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FleetStatsRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait fleet_statsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FleetStatsRow`.
    fn fleet_stats(&self) -> __sdk::__query_builder::Table<FleetStatsRow>;
}

impl fleet_statsQueryTableAccess for __sdk::QueryTableAccessor {
    fn fleet_stats(&self) -> __sdk::__query_builder::Table<FleetStatsRow> {
        __sdk::__query_builder::Table::new("fleet_stats")
    }
}
