// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ingest_message_type::IngestMessage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IngestArgs {
    pub messages: Vec<IngestMessage>,
}

impl From<IngestArgs> for super::Reducer {
    fn from(args: IngestArgs) -> Self {
        Self::Ingest {
            messages: args.messages,
        }
    }
}

impl __sdk::InModule for IngestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ingest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ingest {
    /// Request that the remote module invoke the reducer `ingest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ingest:ingest_then`] to run a callback after the reducer completes.
    fn ingest(&self, messages: Vec<IngestMessage>) -> __sdk::Result<()> {
        self.ingest_then(messages, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ingest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ingest_then(
        &self,
        messages: Vec<IngestMessage>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ingest for super::RemoteReducers {
    fn ingest_then(
        &self,
        messages: Vec<IngestMessage>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(IngestArgs { messages }, callback)
    }
}
