// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::ingest_body_type::IngestBody;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct IngestMessage {
    pub manufacturer: String,
    pub serial_number: String,
    pub sent_at: __sdk::Timestamp,
    pub body: IngestBody,
}

impl __sdk::InModule for IngestMessage {
    type Module = super::RemoteModule;
}
