// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Map {
    pub map_id: String,
    pub name: String,
}

impl __sdk::InModule for Map {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Map`.
///
/// Provides typed access to columns for query building.
pub struct MapCols {
    pub map_id: __sdk::__query_builder::Col<Map, String>,
    pub name: __sdk::__query_builder::Col<Map, String>,
}

impl __sdk::__query_builder::HasCols for Map {
    type Cols = MapCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MapCols {
            map_id: __sdk::__query_builder::Col::new(table_name, "map_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `Map`.
///
/// Provides typed access to indexed columns for query building.
pub struct MapIxCols {
    pub map_id: __sdk::__query_builder::IxCol<Map, String>,
}

impl __sdk::__query_builder::HasIxCols for Map {
    type IxCols = MapIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MapIxCols {
            map_id: __sdk::__query_builder::IxCol::new(table_name, "map_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Map {}
