// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::map_type::Map;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `map`.
///
/// Obtain a handle from the [`MapTableAccess::map`] method on [`super::RemoteTables`],
/// like `ctx.db.map()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map().on_insert(...)`.
pub struct MapTableHandle<'ctx> {
    imp: __sdk::TableHandle<Map>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `map`.
pub struct MapTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for MapTableAccessor {
    type Row = Map;
    type Handle<'db> = MapTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.map()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `map`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MapTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MapTableHandle`], which mediates access to the table `map`.
    fn map(&self) -> MapTableHandle<'_>;
}

impl MapTableAccess for super::RemoteTables {
    fn map(&self) -> MapTableHandle<'_> {
        MapTableHandle {
            imp: self.imp.get_table::<Map>("map"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MapInsertCallbackId(__sdk::CallbackId);
pub struct MapDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for MapTableHandle<'ctx> {
    type Row = Map;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Map> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for MapTableHandle<'ctx> {
    type Row = Map;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Map> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MapInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInsertCallbackId {
        MapInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MapDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapDeleteCallbackId {
        MapDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for MapTableHandle<'ctx> {
    type InsertCallbackId = MapInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapInsertCallbackId {
        MapInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MapInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for MapTableHandle<'ctx> {
    type DeleteCallbackId = MapDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MapDeleteCallbackId {
        MapDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MapDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MapUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MapTableHandle<'ctx> {
    type UpdateCallbackId = MapUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapUpdateCallbackId {
        MapUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for MapTableHandle<'ctx> {
    type UpdateCallbackId = MapUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MapUpdateCallbackId {
        MapUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MapUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `map_id` unique index on the table `map`,
/// which allows point queries on the field of the same name
/// via the [`MapMapIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.map().map_id().find(...)`.
pub struct MapMapIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Map, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MapTableHandle<'ctx> {
    /// Get a handle on the `map_id` unique index on the table `map`.
    pub fn map_id(&self) -> MapMapIdUnique<'ctx> {
        MapMapIdUnique {
            imp: self.imp.get_unique_constraint::<String>("map_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MapMapIdUnique<'ctx> {
    /// Find the subscribed row whose `map_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Map> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Map>("map");
    _table.add_unique_constraint::<String>("map_id", |row| &row.map_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Map>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Map>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Map`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait mapQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Map`.
    fn map(&self) -> __sdk::__query_builder::Table<Map>;
}

impl mapQueryTableAccess for __sdk::QueryTableAccessor {
    fn map(&self) -> __sdk::__query_builder::Table<Map> {
        __sdk::__query_builder::Table::new("map")
    }
}
