// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::agv_state_fields_type::AgvStateFields;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertAgvStateArgs {
    pub manufacturer: String,
    pub serial_number: String,
    pub state: AgvStateFields,
    pub sent_at: __sdk::Timestamp,
}

impl From<UpsertAgvStateArgs> for super::Reducer {
    fn from(args: UpsertAgvStateArgs) -> Self {
        Self::UpsertAgvState {
            manufacturer: args.manufacturer,
            serial_number: args.serial_number,
            state: args.state,
            sent_at: args.sent_at,
        }
    }
}

impl __sdk::InModule for UpsertAgvStateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_agv_state`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_agv_state {
    /// Request that the remote module invoke the reducer `upsert_agv_state` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_agv_state:upsert_agv_state_then`] to run a callback after the reducer completes.
    fn upsert_agv_state(
        &self,
        manufacturer: String,
        serial_number: String,
        state: AgvStateFields,
        sent_at: __sdk::Timestamp,
    ) -> __sdk::Result<()> {
        self.upsert_agv_state_then(manufacturer, serial_number, state, sent_at, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_agv_state` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_agv_state_then(
        &self,
        manufacturer: String,
        serial_number: String,
        state: AgvStateFields,
        sent_at: __sdk::Timestamp,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_agv_state for super::RemoteReducers {
    fn upsert_agv_state_then(
        &self,
        manufacturer: String,
        serial_number: String,
        state: AgvStateFields,
        sent_at: __sdk::Timestamp,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertAgvStateArgs {
                manufacturer,
                serial_number,
                state,
                sent_at,
            },
            callback,
        )
    }
}
