// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::connection_state_type::ConnectionState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertAgvConnectionArgs {
    pub manufacturer: String,
    pub serial_number: String,
    pub connection_state: ConnectionState,
    pub sent_at: __sdk::Timestamp,
}

impl From<UpsertAgvConnectionArgs> for super::Reducer {
    fn from(args: UpsertAgvConnectionArgs) -> Self {
        Self::UpsertAgvConnection {
            manufacturer: args.manufacturer,
            serial_number: args.serial_number,
            connection_state: args.connection_state,
            sent_at: args.sent_at,
        }
    }
}

impl __sdk::InModule for UpsertAgvConnectionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_agv_connection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_agv_connection {
    /// Request that the remote module invoke the reducer `upsert_agv_connection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_agv_connection:upsert_agv_connection_then`] to run a callback after the reducer completes.
    fn upsert_agv_connection(
        &self,
        manufacturer: String,
        serial_number: String,
        connection_state: ConnectionState,
        sent_at: __sdk::Timestamp,
    ) -> __sdk::Result<()> {
        self.upsert_agv_connection_then(
            manufacturer,
            serial_number,
            connection_state,
            sent_at,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `upsert_agv_connection` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_agv_connection_then(
        &self,
        manufacturer: String,
        serial_number: String,
        connection_state: ConnectionState,
        sent_at: __sdk::Timestamp,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_agv_connection for super::RemoteReducers {
    fn upsert_agv_connection_then(
        &self,
        manufacturer: String,
        serial_number: String,
        connection_state: ConnectionState,
        sent_at: __sdk::Timestamp,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertAgvConnectionArgs {
                manufacturer,
                serial_number,
                connection_state,
                sent_at,
            },
            callback,
        )
    }
}
