// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertMapArgs {
    pub map_id: String,
    pub name: Option<String>,
}

impl From<UpsertMapArgs> for super::Reducer {
    fn from(args: UpsertMapArgs) -> Self {
        Self::UpsertMap {
            map_id: args.map_id,
            name: args.name,
        }
    }
}

impl __sdk::InModule for UpsertMapArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_map`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_map {
    /// Request that the remote module invoke the reducer `upsert_map` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_map:upsert_map_then`] to run a callback after the reducer completes.
    fn upsert_map(&self, map_id: String, name: Option<String>) -> __sdk::Result<()> {
        self.upsert_map_then(map_id, name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_map` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_map_then(
        &self,
        map_id: String,
        name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_map for super::RemoteReducers {
    fn upsert_map_then(
        &self,
        map_id: String,
        name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpsertMapArgs { map_id, name }, callback)
    }
}
