// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpsertAgvArgs {
    pub manufacturer: String,
    pub serial_number: String,
    pub map_id: String,
}

impl From<UpsertAgvArgs> for super::Reducer {
    fn from(args: UpsertAgvArgs) -> Self {
        Self::UpsertAgv {
            manufacturer: args.manufacturer,
            serial_number: args.serial_number,
            map_id: args.map_id,
        }
    }
}

impl __sdk::InModule for UpsertAgvArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `upsert_agv`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait upsert_agv {
    /// Request that the remote module invoke the reducer `upsert_agv` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`upsert_agv:upsert_agv_then`] to run a callback after the reducer completes.
    fn upsert_agv(
        &self,
        manufacturer: String,
        serial_number: String,
        map_id: String,
    ) -> __sdk::Result<()> {
        self.upsert_agv_then(manufacturer, serial_number, map_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `upsert_agv` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn upsert_agv_then(
        &self,
        manufacturer: String,
        serial_number: String,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl upsert_agv for super::RemoteReducers {
    fn upsert_agv_then(
        &self,
        manufacturer: String,
        serial_number: String,
        map_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpsertAgvArgs {
                manufacturer,
                serial_number,
                map_id,
            },
            callback,
        )
    }
}
