// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::connection_state_type::ConnectionState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UpsertAgvConnection {
    pub manufacturer: String,
    pub serial_number: String,
    pub connection_state: ConnectionState,
    pub sent_at: __sdk::Timestamp,
}

impl __sdk::InModule for UpsertAgvConnection {
    type Module = super::RemoteModule;
}
