// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ConnectionState,
} from "./types";


export default __t.row({
  agvId: __t.string().primaryKey().name("agv_id"),
  get connectionState() {
    return ConnectionState.name("connection_state");
  },
  sentAt: __t.timestamp().name("sent_at"),
});
