// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AgvError,
  ConnectionState,
} from "./types";


export default __t.row({
  agvId: __t.string().primaryKey().name("agv_id"),
  orderId: __t.string().name("order_id"),
  lastNodeId: __t.string().name("last_node_id"),
  get error() {
    return __t.option(AgvError);
  },
  get connectionState() {
    return ConnectionState.name("connection_state");
  },
  updatedAt: __t.timestamp().name("updated_at"),
  alert: __t.bool(),
  stateSentAt: __t.option(__t.timestamp()).name("state_sent_at"),
  connectionSentAt: __t.option(__t.timestamp()).name("connection_sent_at"),
});
