// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agv = __t.object("Agv", {
  agvId: __t.string(),
  manufacturer: __t.string(),
  serialNumber: __t.string(),
  mapId: __t.string(),
});
export type Agv = __Infer<typeof Agv>;

export const AgvConnection = __t.object("AgvConnection", {
  agvId: __t.string(),
  get connectionState() {
    return ConnectionState;
  },
  sentAt: __t.timestamp(),
});
export type AgvConnection = __Infer<typeof AgvConnection>;

export const AgvError = __t.object("AgvError", {
  errorType: __t.string(),
  get errorLevel() {
    return ErrorLevel;
  },
});
export type AgvError = __Infer<typeof AgvError>;

export const AgvPage = __t.object("AgvPage", {
  agvIds: __t.array(__t.string()),
  nextAgvId: __t.option(__t.string()),
});
export type AgvPage = __Infer<typeof AgvPage>;

export const AgvState = __t.object("AgvState", {
  agvId: __t.string(),
  orderId: __t.string(),
  lastNodeId: __t.string(),
  driving: __t.bool(),
  paused: __t.bool(),
  charging: __t.bool(),
  get error() {
    return __t.option(AgvError);
  },
  updatedAt: __t.timestamp(),
  alert: __t.bool(),
  stateSentAt: __t.timestamp(),
});
export type AgvState = __Infer<typeof AgvState>;

export const AgvStateFields = __t.object("AgvStateFields", {
  orderId: __t.string(),
  lastNodeId: __t.string(),
  driving: __t.bool(),
  paused: __t.bool(),
  charging: __t.bool(),
  get error() {
    return __t.option(AgvError);
  },
});
export type AgvStateFields = __Infer<typeof AgvStateFields>;

// The tagged union or sum type for the algebraic type `ConnectionState`.
export const ConnectionState = __t.enum("ConnectionState", {
  Online: __t.unit(),
  Offline: __t.unit(),
  Connectionbroken: __t.unit(),
});
export type ConnectionState = __Infer<typeof ConnectionState>;

// The tagged union or sum type for the algebraic type `ErrorLevel`.
export const ErrorLevel = __t.enum("ErrorLevel", {
  Warning: __t.unit(),
  Fatal: __t.unit(),
});
export type ErrorLevel = __Infer<typeof ErrorLevel>;

export const FleetStats = __t.object("FleetStats", {});
export type FleetStats = __Infer<typeof FleetStats>;

export const FleetStatsRow = __t.object("FleetStatsRow", {
  sites: __t.u64(),
  agvs: __t.u64(),
  online: __t.u64(),
  alerts: __t.u64(),
});
export type FleetStatsRow = __Infer<typeof FleetStatsRow>;

// The tagged union or sum type for the algebraic type `IngestBody`.
export const IngestBody = __t.enum("IngestBody", {
  get State() {
    return IngestState;
  },
  get Connection() {
    return ConnectionState;
  },
});
export type IngestBody = __Infer<typeof IngestBody>;

export const IngestMessage = __t.object("IngestMessage", {
  manufacturer: __t.string(),
  serialNumber: __t.string(),
  sentAt: __t.timestamp(),
  get body() {
    return IngestBody;
  },
});
export type IngestMessage = __Infer<typeof IngestMessage>;

export const IngestState = __t.object("IngestState", {
  mapId: __t.option(__t.string()),
  get state() {
    return AgvStateFields;
  },
});
export type IngestState = __Infer<typeof IngestState>;

export const Map = __t.object("Map", {
  mapId: __t.string(),
  name: __t.string(),
});
export type Map = __Infer<typeof Map>;

