// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AgvPageProcedure from "../agv_page_procedure";

export type AgvPageArgs = __Infer<typeof AgvPageProcedure.params>;
export type AgvPageResult = __Infer<typeof AgvPageProcedure.returnType>;

