// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import UpsertAgvReducer from "../upsert_agv_reducer";
import UpsertAgvConnectionReducer from "../upsert_agv_connection_reducer";
import UpsertAgvStateReducer from "../upsert_agv_state_reducer";
import UpsertMapReducer from "../upsert_map_reducer";

export type UpsertAgvParams = __Infer<typeof UpsertAgvReducer>;
export type UpsertAgvConnectionParams = __Infer<typeof UpsertAgvConnectionReducer>;
export type UpsertAgvStateParams = __Infer<typeof UpsertAgvStateReducer>;
export type UpsertMapParams = __Infer<typeof UpsertMapReducer>;

